name: CI
on: [push]
jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm i
      - name: Run lint
        run: npm run lint -- --max-warnings=0
