name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install packages
        run: npm ci
      - name: Run lint
        run: npm run lint -- --max-warnings=0
