name: Pipeline workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        env:
          SKIP_ENV_VALIDATION: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Set up database
        run: npm run test:db-up

      - name: Run integration tests
        run: npm run test:integration
        env:
          SKIP_ENV_VALIDATION: true

      - name: Run E2E tests
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
        env:
          SKIP_ENV_VALIDATION: true
          NEXTAUTH_SECRET: SECRET
          NEXTAUTH_URL: http://localhost:3000
          DATABASE_URL: mysql://prisma:prisma@localhost:3306/tests

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: checks

    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.DEPLOYMENT_ACCESS_TOKEN }}
          env: production

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: '--prod'

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.DEPLOYMENT_ACCESS_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
